apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: experiment

configMapGenerator:
- envs:
  - metrics-processor.env
  name: metrics-processor-env
- envs:
  - experiment-runner.env
  name: experiment-runner-env
- name: lg-script
  files:
  - script.js


generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    group: batch
    version: v1
    kind: Job
    name: experiment-runner
  path: job-patch.yaml
