---
apiVersion: batch/v1
kind: Job
metadata:
  name: experiment-runner
spec:
  template:
    spec:
      serviceAccountName: experiment-runner-serviceaccount
      containers:
      - name: experiment-runner
        image: docker.io/hiroki11hanada/experiment-runner:v1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: experiment-runner-env
      restartPolicy: Never
