metadata:
  creationTimestamp: null
  name: test-11-26-00-20-03
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: aws-credentials
        - name: S3_KEY
          value: test
        - name: DURATION
          value: 30m
        - name: TZ
          value: Asia/Tokyo
        envFrom:
        - configMapRef:
            name: metrics-processor
        image: metrics-processor:v1.0.0
        name: test-11-26-00-20-03
        resources: {}
      restartPolicy: Never
status: {}
